import React from 'react';
import ReactDOM from 'react-dom';
// import App from './App';
import registerServiceWorker from './registerServiceWorker';
import './index.css';
// import Header from './components/Header/Header';
// import Btn from  './components/Btn';
// import Show from './components/Show';
import Show from './components/Show';
import Tab from './components/Tab';
import Holle from './components/Holle';
import Head from './components/Head';
import Dad from './components/Dad';
// import New from "./components/New/New";
// import New from "./components/Newo";
import Xw from "./components/Xw";
import Routerlist from "./components/Routerlist";
import Btn2 from "./components/Btn2/Btn2";
import Main from "./components/Main";
// import Lbt from "./components/Main/Lbt";
// ReactDOM.render(<div><Header/> <App/><Show/></div>,document.getElementById('root'));
// ReactDOM.render(<div><Show/></div>,document.getElementById('root'));
// ReactDOM.render(<div><Tab/><Holle name="啊啊啊啊啊"/><Head username="tom"/></div>,document.getElementById('root'));
// ReactDOM.render(<div><Dad/></div>,document.getElementById('root'));
// ReactDOM.render(<div><New/></div>,document.getElementById('root'));
// ReactDOM.render(<div><Xw/></div>,document.getElementById('root'));
// ReactDOM.render(<div><New/></div>,document.getElementById('root'));
// ReactDOM.render(<div><Btn2/></div>,document.getElementById('root'));
// ReactDOM.render(<div><Main/></div>,document.getElementById('root'));
ReactDOM.render(<div><Main/></div>,document.getElementById('root'));
registerServiceWorker();
